-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 10:09:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema centreFormation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etudiant` (
  `numCINEtu` VARCHAR(10) NOT NULL,
  `nomEtu` VARCHAR(45) NULL,
  `prenomEtu` VARCHAR(45) NULL,
  `datenais` DATE NULL,
  `villeEtu` VARCHAR(45) NULL,
  `niveauEtu` VARCHAR(45) NULL,
  PRIMARY KEY (`numCINEtu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formation` (
  `codeForm` INT NOT NULL,
  `titreForm` VARCHAR(45) NULL,
  `dureeForm` DECIMAL(5) NULL,
  `prixForm` DECIMAL(5) NULL,
  PRIMARY KEY (`codeForm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `session` (
  `codeSess` INT NOT NULL,
  `nomsess` VARCHAR(45) NULL,
  `datedebut` DATE NULL,
  `codeForm` VARCHAR(10) NULL,
  `dateFin` DATE NULL,
  `formation_codeForm` INT NOT NULL,
  PRIMARY KEY (`codeSess`),
  INDEX `CHECK` () COMMENT 'dateFin > datedebut' VISIBLE,
  INDEX `fk_session_formation1_idx` (`formation_codeForm` ASC) VISIBLE,
  CONSTRAINT `codeForm`
    FOREIGN KEY ()
    REFERENCES `formation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_formation1`
    FOREIGN KEY (`formation_codeForm`)
    REFERENCES `formation` (`codeForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inscription` (
  `codesess` INT NOT NULL,
  `numCINEtu` VARCHAR(10) NOT NULL,
  `typeCours` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codesess`, `numCINEtu`),
  CONSTRAINT `codesess`
    FOREIGN KEY ()
    REFERENCES `session` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numCINEtu`
    FOREIGN KEY ()
    REFERENCES `etudiant` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `specialite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `specialite` (
  `codeSpec` INT NOT NULL,
  `nomSpec` VARCHAR(45) NULL,
  `descSpec` VARCHAR(100) NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`codeSpec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `combinaison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `combinaison` (
  `codeSpec` INT NOT NULL,
  `codeForm` INT NOT NULL,
  PRIMARY KEY (`codeSpec`, `codeForm`),
  CONSTRAINT `codeSpec`
    FOREIGN KEY ()
    REFERENCES `specialite` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codeForm`
    FOREIGN KEY ()
    REFERENCES `formation` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
